// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0WVUGfcUw8ZZ7JKlVs8OSvsPXK2kt2Zo',
    appId: '1:623836444601:web:c510f289782b336b506868',
    messagingSenderId: '623836444601',
    projectId: 'm1-app-aedb0',
    authDomain: 'm1-app-aedb0.firebaseapp.com',
    storageBucket: 'm1-app-aedb0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpR_scWb85prb0ZWFZm_ZuCm5Gdx5UwRs',
    appId: '1:623836444601:android:fa5442ce38dc2e6e506868',
    messagingSenderId: '623836444601',
    projectId: 'm1-app-aedb0',
    storageBucket: 'm1-app-aedb0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9bk9Vf9MYFiE16AjO9FkHNEnIMo1RMWI',
    appId: '1:623836444601:ios:4a74ecc65b65a67d506868',
    messagingSenderId: '623836444601',
    projectId: 'm1-app-aedb0',
    storageBucket: 'm1-app-aedb0.firebasestorage.app',
    iosBundleId: 'com.example.flutterQuizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9bk9Vf9MYFiE16AjO9FkHNEnIMo1RMWI',
    appId: '1:623836444601:ios:4a74ecc65b65a67d506868',
    messagingSenderId: '623836444601',
    projectId: 'm1-app-aedb0',
    storageBucket: 'm1-app-aedb0.firebasestorage.app',
    iosBundleId: 'com.example.flutterQuizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0WVUGfcUw8ZZ7JKlVs8OSvsPXK2kt2Zo',
    appId: '1:623836444601:web:91e75d4f156c2246506868',
    messagingSenderId: '623836444601',
    projectId: 'm1-app-aedb0',
    authDomain: 'm1-app-aedb0.firebaseapp.com',
    storageBucket: 'm1-app-aedb0.firebasestorage.app',
  );
}
